URL_CLIENTE_WS = 'http://proyectocinews-jhuaman.rhcloud.com/services/ClienteDaoImpl?wsdl'
URL_RESERVA_WS = 'http://proyectocinews-jhuaman.rhcloud.com/services/ReservaDaoImpl?wsdl'
URL_CIUDAD_WS = 'http://proyectocinews-jhuaman.rhcloud.com/services/CiudadDaoImpl?wsdl'
URL_CARTELERA_WS = 'http://proyectocinews-jhuaman.rhcloud.com/services/CarteleraDaoImpl?wsdl'
URL_COMPLEJO_WS = 'http://proyectocinews-jhuaman.rhcloud.com/services/ComplejoDaoImpl?wsdl'
URL_RESERVA_BUTACA_WS = 'http://proyectocinews-jhuaman.rhcloud.com/services/ReservaButacaDaoImpl?wsdl'
